version: '2'

volumes:
  postgres-data:
    driver: local

services:
  db:
    image: postgres:9.5.1
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: P4Ssw0rD!

  app: &base
    image: thelastinuit/utron:1.0
    command: bash
    working_dir: /usr/src/
    volumes:
      - .:/usr/src
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:P4Ssw0rD!@db:5432/ultron_dev?sslmode=disable
  web:
    <<: *base
    entrypoint: /usr/src/development-entrypoint.sh
    ports:
      - 80:80
    command: go run main.go

  test:
    <<: *base
    entrypoint: /usr/src/test-entrypoint.sh
    command: goconvey -host=0.0.0.0
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:P4Ssw0rD!@db:5432/ultron_test?sslmode=disable
